name: QuietZones
version: ${project.version}
main: quietzones.Main
api-version: "1.17"
authors: [nickrodi]
description: Mute entity sounds in specific zones of a world (so farms can be noise-free!)

commands:
  qz:
    description: Quiet zone management command
    usage: /qz
    permission: quietzones.manage

permissions:
  quietzones.manage:
    description: Allows player to manage quiet zones
    default: op
